# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#about-the-dependabotyml-file
#
# Configure dependabot to maintain dependencies.

version: 2

#registries:
#
#  dockerhub: # Define access for a private registry 
#    type: docker-registry
#    url: registry.hub.docker.com
#    username: octocat
#    password: ${{secrets.DOCKERHUB_PASSWORD}}

updates:

#  - package-ecosystem: "docker"
#    directory: "/docker-registry/dockerhub"
#    registries:
#      - dockerhub # Allow version updates for dependencies in this registry
#    schedule:
#      interval: "monthly"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the default `.github/workflows` directory
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
